# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0002_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.CharField(default='', max_length=300),
        ),
    ]
