# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0004_auto_20170425_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='panda_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(10, 'draft'), (20, 'ready'), (30, 'jobs ready'), (40, 'send'), (50, 'running'), (60, 'paused'), (70, 'cancelled'), (80, 'done')], default=10),
        ),
    ]
