# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0005_auto_20170426_0438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('task', 'file')]),
        ),
    ]
