# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0007_auto_20170427_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chunk_number',
            field=models.IntegerField(default=0),
        ),
    ]
