# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0008_job_chunk_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='soft',
            field=models.CharField(max_length=300),
        ),
    ]
