# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0009_auto_20170427_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slot',
        ),
    ]
