# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0010_remove_task_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.CharField(choices=[(10, 'test production'), (20, 'mass production')], default='template.opt', max_length=50),
        ),
    ]
