# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0011_auto_20170427_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.CharField(choices=[('template.opt', 'template.opt'), ('template_mu+.opt', 'template_mu+.opt'), ('template_mu-.opt', 'template_mu-.opt')], default='template.opt', max_length=50),
        ),
    ]
