# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0012_auto_20170427_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='year',
        ),
    ]
