# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0014_auto_20170503_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
