# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0015_auto_20170503_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='home',
            field=models.CharField(default='/cvmfs/compass.cern.ch/', max_length=300),
        ),
    ]
