# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0018_auto_20170522_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(10, 'defined'), (20, 'sent'), (30, 'running'), (40, 'failed'), (50, 'paused'), (60, 'cancelled'), (70, 'merging'), (80, 'merged'), (90, 'x-checking'), (100, 'x-checked'), (110, 'done'), (120, 'manual check is needed')], default=10),
        ),
    ]
