# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0020_auto_20170522_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('defined', 'defined'), ('sent', 'sent'), ('running', 'running'), ('failed', 'failed'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('merging', 'merging'), ('merged', 'merged'), ('x-checking', 'x-checking'), ('x-checked', 'x-checked'), ('finished', 'finished'), ('manual check is needed', 'manual check is needed')], default='defined', max_length=300),
        ),
    ]
