# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0021_auto_20170522_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('jobs ready', 'jobs ready'), ('send', 'send'), ('running', 'running'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('done', 'done')], default='draft', max_length=300),
        ),
    ]
