# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0022_auto_20170522_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attempt_merge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='panda_id_merge',
            field=models.BigIntegerField(default=0),
        ),
    ]
