# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0024_auto_20170626_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chunk_number_merging',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
