# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0026_auto_20170626_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='chunk_number_merging',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
