# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0028_auto_20170626_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_x_check',
            field=models.CharField(default='no', max_length=300),
        ),
    ]
