# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0029_job_status_x_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('defined', 'defined'), ('sent', 'sent'), ('running', 'running'), ('failed', 'failed'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('manual check is needed', 'manual check is needed')], default='defined', max_length=300),
        ),
    ]
