# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0030_auto_20170706_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='attempt_merging',
            new_name='attempt_merging_mdst',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='chunk_number_merging',
            new_name='chunk_number_merging_mdst',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='panda_id_merging',
            new_name='panda_id_merging_mdst',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='status_merging',
            new_name='status_merging_mdst',
        ),
    ]
