# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0032_auto_20170707_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='chunk_number_merging_evntdmp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='chunk_number_merging_histos',
        ),
    ]
