# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0035_auto_20170816_1512'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['task', 'file', 'run_number', 'chunk_number', 'panda_id', 'attempt', 'status', ], name='prodsys_job_task_id_ecfe97_idx'),
        ),
    ]
