# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0036_auto_20170816_1513'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='prodsys_job_task_id_ecfe97_idx',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['task', 'file', 'run_number', 'chunk_number', 'panda_id', 'attempt', 'status', 'status_x_check'], name='prodsys_job_task_id_853b0d_idx'),
        ),
    ]
