# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0039_auto_20170816_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('task', 'file')]),
        ),
    ]
