# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0044_auto_20170901_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(10, 'test production'), (20, 'mass production'), (30, 'DDD filtering')], default=10),
        ),
    ]
