# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0048_auto_20170906_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('task', 'file')]),
        ),
    ]
