# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0051_auto_20170915_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='production',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
