# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0053_auto_20171019_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='production',
        ),
    ]
