# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0054_remove_task_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='production',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
