# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0055_task_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='production',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
