# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0056_auto_20171019_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='production',
            field=models.CharField(max_length=50),
        ),
    ]
