# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0058_job_status_castor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status_castor',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
