# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0061_auto_20171023_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status_castor_evntdmp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_castor_histos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_castor_mdst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
