# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0063_auto_20171031_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chunk_number_merging_evntdmp',
            field=models.IntegerField(default=-1),
        ),
    ]
