# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0065_job_status_x_check_evntdmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('defined', 'defined'), ('staged', 'staged'), ('sent', 'sent'), ('running', 'running'), ('failed', 'failed'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('manual check is needed', 'manual check is needed')], default='defined', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_merging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_merging_evntdmp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_merging_histos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_merging_mdst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_x_check',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
