# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0066_auto_20171104_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files_source',
            field=models.CharField(choices=[('files list', 'files list'), ('runs list', 'runs list')], default='files list', max_length=50),
        ),
    ]
