# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0068_job_number_of_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='site',
            field=models.CharField(choices=[('CERN_COMPASS_PROD', 'CERN_COMPASS_PROD'), ('BW_COMPASS_MCORE', 'BW_COMPASS_MCORE')], default='CERN_COMPASS_PROD', max_length=50),
        ),
    ]
