# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0069_task_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='number_of_events',
            field=models.IntegerField(default=-1),
        ),
    ]
