# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0070_auto_20180311_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files_home',
            field=models.CharField(blank=True, help_text='For BlueWaters only', max_length=300, null=True),
        ),
    ]
