# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0072_auto_20180508_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('defined', 'defined'), ('staging', 'staging'), ('staged', 'staged'), ('sent', 'sent'), ('running', 'running'), ('failed', 'failed'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('manual check is needed', 'manual check is needed')], default='defined', max_length=50),
        ),
    ]
