# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0073_auto_20180521_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chunk_number_merging_histos',
            field=models.IntegerField(default=-1),
        ),
    ]
