# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0075_job_logs_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='home',
            field=models.CharField(default='/cvmfs/compass.cern.ch/', help_text='mandatory leading and trailing slashes', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.CharField(help_text='no leading slash, mandatory trailing slash', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('test production', 'test production'), ('mass production', 'mass production'), ('technical production', 'technical production'), ('DDD filtering', 'DDD filtering')], default='test production', max_length=50),
        ),
    ]
