# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0077_auto_20180802_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='home',
            field=models.CharField(default='/cvmfs/compass.cern.ch/', help_text='mandatory leading and trailing slash', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='soft',
            field=models.CharField(help_text='no leading and trailing slash', max_length=300),
        ),
    ]
