# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0079_auto_20180829_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attempt_logs_castor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='status_logs_archived',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='job',
            name='status_logs_castor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
