# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0081_auto_20181119_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_processing_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_processing_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
