# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0082_auto_20181206_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('test production', 'test production'), ('mass production', 'mass production'), ('technical production', 'technical production'), ('DDD filtering', 'DDD filtering'), ('MC generation', 'MC generation'), ('MC reconstruction', 'MC reconstruction')], default='test production', max_length=50),
        ),
    ]
