# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0083_auto_20190411_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='task_name',
        ),
    ]
