# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0084_remove_job_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_events_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
