# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0085_job_number_of_events_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_files_deleted',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
