# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0088_auto_20190813_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sw_prefix',
            new_name='files_home_prefix',
        ),
    ]
