# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0089_auto_20190813_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='use_local_generator_file',
            field=models.CharField(choices=[('yes', 'no'), ('yes', 'no')], default='yes', max_length=5),
        ),
    ]
