# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0091_auto_20190910_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files_home',
            field=models.CharField(blank=True, help_text='For HPC only, mandatory leading and trailing slash', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='files_home_prefix',
            field=models.CharField(blank=True, help_text='For HPC only, mandatory leading and trailing slash', max_length=300, null=True),
        ),
    ]
