# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0094_auto_20191022_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attempt_castor_mcgen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='status_castor_mcgen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
