# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0097_auto_20191029_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_task_id',
            new_name='parent_task',
        ),
    ]
