# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0098_auto_20191029_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='filelist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
