# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0099_auto_20191030_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
