# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0100_auto_20191030_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodsys.Task'),
        ),
    ]
