# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0102_auto_20191119_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_panda_job_deleted',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
