# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0103_task_status_panda_job_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status_panda_job_deleted',
        ),
        migrations.AddField(
            model_name='job',
            name='status_panda_job_deleted',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
