# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0104_auto_20191203_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='site',
            field=models.CharField(choices=[('CERN_COMPASS_PROD', 'CERN_COMPASS_PROD'), ('BW_COMPASS_MCORE', 'BW_COMPASS_MCORE'), ('STAMPEDE_COMPASS_MCORE', 'STAMPEDE_COMPASS_MCORE'), ('FRONTERA_COMPASS_MCORE', 'FRONTERA_COMPASS_MCORE'), ('FRONTERA_COMPASS_TEST', 'FRONTERA_COMPASS_TEST')], default='CERN_COMPASS_PROD', max_length=50),
        ),
    ]
