# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0105_auto_20200406_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_failed_jobs_deleted',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('jobs ready', 'jobs ready'), ('send', 'send'), ('resend failed', 'resend failed'), ('resend staging', 'resend staging'), ('resend manual check', 'resend manual check'), ('running', 'running'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('done', 'done'), ('archive', 'archive'), ('archiving', 'archiving'), ('archived', 'archived')], default='draft', max_length=300),
        ),
    ]
