# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0106_auto_20210126_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tapes_backend',
            field=models.CharField(default='castor', max_length=6),
        ),
    ]
