# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-31 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodsys', '0107_task_tapes_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cta_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tapes_backend',
            field=models.CharField(choices=[('castor', 'castor'), ('cta', 'cta')], default='castor', max_length=6),
        ),
    ]
